function getData(){
	var dataAMZ = {
	B07D9FB15R: {US: "https://amzn.to/2DMThHH",CA: "",UK: ""},
	B07VVM1VM6: {US: "https://amzn.to/3kDJvYY ",CA: "",UK: ""},
	B07SDQ2NB7: {US: "https://amzn.to/2DDurtX",CA: "",UK: ""},
	B00SOR41CO: {US: "https://amzn.to/33ZnHku",CA: "",UK: ""},
	B06Y2LQ5QJ: {US: "https://amzn.to/3kFuBBF",CA: "",UK: ""},
	B07HHP2JD8: {US: "https://amzn.to/33TAO6V",CA: "",UK: ""},
	B07HHNSL5H: {US: "https://amzn.to/2FbCLBg",CA: "",UK: ""},
	B00IJ0ALYS: {US: "https://amzn.to/2DVv1mo",CA: "",UK: ""},
	B0194RLK4Y: {US: "https://amzn.to/33Vwm7S",CA: "",UK: ""},
	B01DLYQ4DS: {US: "https://amzn.to/2DGo1Ky",CA: "",UK: ""},
	B078SQSNV7: {US: "https://amzn.to/2E1sM16",CA: "",UK: ""},
	B004918MO2: {US: "https://amzn.to/30TzMWN",CA: "",UK: ""},
	B001BMDFPS: {US: "https://amzn.to/2POgQ5u",CA: "",UK: ""},
	B0088PTF3M: {US: "https://amzn.to/30OLKAW",CA: "",UK: ""},
	B07F6PDQP6: {US: "https://amzn.to/30SEkwt",CA: "",UK: ""},
	B085WD92Q4: {US: "https://amzn.to/2DOcJDN",CA: "",UK: ""},
	B07F88P35C: {US: "https://amzn.to/3iy1Rc0",CA: "",UK: ""},
	B07VVM1VM6: {US: "https://amzn.to/3kDJvYY",CA: "",UK: ""},
	B07D9FB15R: {US: "https://amzn.to/2DMThHH",CA: "",UK: ""},
	B07QLVHBLF: {US: "https://amzn.to/3aj0zi4",CA: "",UK: ""},
	B07QTVMWVL: {US: "https://amzn.to/2PJSM3s",CA: "",UK: ""},
	B07H4JD85M: {US: "https://amzn.to/31P4sr8",CA: "",UK: ""},
	B07YFBW4W3: {US: "https://amzn.to/3ixFAv1",CA: "",UK: ""},
	B076FDQC2P: {US: "https://amzn.to/3kCqqGx",CA: "",UK: ""},
	B001ASTHJG: {US: "https://amzn.to/3iGMyOt",CA: "",UK: ""},
	B002R8CPRY: {US: "https://amzn.to/3fPIp92",CA: "",UK: ""},
	B00J0S0JGS: {US: "https://amzn.to/2XXwhfV",CA: "",UK: ""},
	B07HQRSQQT: {US: "https://amzn.to/33UlXt2",CA: "",UK: ""},
	B0000C16R8: {US: "https://amzn.to/2DPWDJT",CA: "",UK: ""},
	B07BDN8PML: {US: "https://amzn.to/2XQuedF",CA: "",UK: ""},
	B01MUP6L1U: {US: "https://amzn.to/2PQ6ulv",CA: "",UK: ""},
	B082P6G15G: {US: "https://amzn.to/2FnwpiB",CA: "",UK: ""},
	B078MPFN55: {US: "https://amzn.to/3ixPOvp",CA: "",UK: ""},
	B00TL72F2E: {US: "https://amzn.to/2DQ3HWV",CA: "",UK: ""},
	B07H4JD85M: {US: "https://amzn.to/31P4sr8",CA: "",UK: ""},
	B00FMUYU6I: {US: "https://amzn.to/3fWpcSW",CA: "",UK: ""},
	B07PB4HJLZ: {US: "https://amzn.to/3aiK1qH",CA: "",UK: ""},
	B0012TCFBA: {US: "https://amzn.to/3gT9ysJ",CA: "",UK: ""},
	B00JYUXUZO: {US: "https://amzn.to/3iCZWD3",CA: "",UK: ""},
	B07NQPLB1Q: {US: "https://amzn.to/3gTOsun",CA: "",UK: ""},
	B00IVF9WL4: {US: "https://amzn.to/3asFBxy",CA: "",UK: ""}
	}
	return dataAMZ;
}
